=begin
#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 7.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

# Common files
require 'kie_client/api_client'
require 'kie_client/api_error'
require 'kie_client/version'
require 'kie_client/configuration'

# Models
require 'kie_client/models/case_adhoc_fragment'
require 'kie_client/models/case_adhoc_fragment_list'
require 'kie_client/models/case_comment'
require 'kie_client/models/case_comment_list'
require 'kie_client/models/case_definition'
require 'kie_client/models/case_definition_list'
require 'kie_client/models/case_file'
require 'kie_client/models/case_instance'
require 'kie_client/models/case_instance_list'
require 'kie_client/models/case_migration_report_instance'
require 'kie_client/models/case_milestone'
require 'kie_client/models/case_milestone_def'
require 'kie_client/models/case_milestone_list'
require 'kie_client/models/case_role_assignment'
require 'kie_client/models/case_role_assignment_list'
require 'kie_client/models/case_stage'
require 'kie_client/models/case_stage_def'
require 'kie_client/models/case_stage_list'
require 'kie_client/models/document_instance'
require 'kie_client/models/document_instance_list'
require 'kie_client/models/error_info_instance'
require 'kie_client/models/error_info_instance_list'
require 'kie_client/models/execution_error'
require 'kie_client/models/execution_error_list'
require 'kie_client/models/kie_message'
require 'kie_client/models/migration_report_instance'
require 'kie_client/models/migration_report_instance_list'
require 'kie_client/models/node_instance'
require 'kie_client/models/node_instance_list'
require 'kie_client/models/process_associated_entities'
require 'kie_client/models/process_definition'
require 'kie_client/models/process_definitions'
require 'kie_client/models/process_instance'
require 'kie_client/models/process_instance_list'
require 'kie_client/models/process_node'
require 'kie_client/models/process_node_list'
require 'kie_client/models/process_service_tasks'
require 'kie_client/models/process_subprocesses'
require 'kie_client/models/process_task_inputs'
require 'kie_client/models/process_task_outputs'
require 'kie_client/models/process_variables'
require 'kie_client/models/query_definition'
require 'kie_client/models/query_definitions'
require 'kie_client/models/request_info_instance'
require 'kie_client/models/request_info_instance_list'
require 'kie_client/models/response'
require 'kie_client/models/responses'
require 'kie_client/models/score_wrapper'
require 'kie_client/models/solver_instance'
require 'kie_client/models/solvers'
require 'kie_client/models/task_attachment'
require 'kie_client/models/task_attachment_list'
require 'kie_client/models/task_comment'
require 'kie_client/models/task_comment_list'
require 'kie_client/models/task_event_instance'
require 'kie_client/models/task_event_instance_list'
require 'kie_client/models/task_instance'
require 'kie_client/models/task_notification'
require 'kie_client/models/task_notification_list'
require 'kie_client/models/task_reassignment'
require 'kie_client/models/task_reassignment_list'
require 'kie_client/models/task_summary'
require 'kie_client/models/task_summary_list'
require 'kie_client/models/timer_instance'
require 'kie_client/models/timer_instance_list'
require 'kie_client/models/user_task_definition'
require 'kie_client/models/user_task_definitions'
require 'kie_client/models/variable_instance'
require 'kie_client/models/variable_instance_list'
require 'kie_client/models/work_item_instance'
require 'kie_client/models/work_item_instance_list'

# APIs
require 'kie_client/api/administration_of_cases_case_management_api'
require 'kie_client/api/asynchronous_jobs_bpm_api'
require 'kie_client/api/case_instances_case_management_api'
require 'kie_client/api/custom_queries_bpm_api'
require 'kie_client/api/decision_service_dmn_api'
require 'kie_client/api/documents_bpm_api'
require 'kie_client/api/kie_server_core_api'
require 'kie_client/api/kie_server_script_core_api'
require 'kie_client/api/planning_and_solvers_brp_api'
require 'kie_client/api/process_and_task_definitions_bpm_api'
require 'kie_client/api/process_and_task_forms_bpm_api'
require 'kie_client/api/process_definition_and_instance_images_bpm_api'
require 'kie_client/api/process_instances_administration_bpm_api'
require 'kie_client/api/process_instances_bpm_api'
require 'kie_client/api/queries_case_definitions_and_instances_case_management_api'
require 'kie_client/api/queries_processes_nodes_variables_and_tasks_bpm_api'
require 'kie_client/api/rules_evaluation_brm_api'
require 'kie_client/api/user_task_operations_and_queries_bpm_api'
require 'kie_client/api/user_tasks_administration_bpm_api'

module KieClient
  class << self
    # Customize default settings for the SDK using block.
    #   KieClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
